### ISSUE TITLE
save($entity) must be compatible with CodeIgniter\Model::save($data)

### ISSUE THREAD

**Issue by arashsaffari** [4spacesdk/CI4OrmExtension#1]
I wanted to use CI4Orm Extension but I get the error message: Fatal error: Declaration of OrmExtension\Extensions\Model::save($entity) must be compatible with CodeIgniter\Model::save($data): bool in /Users/XXXX/Datein/Web Server/htdocs/project/vendor/4spacesdk/ci4ormextension/Extensions/Model.php on line 34

can you help me please?

**Comment by Martin-4Spaces** [comment]
@arashsaffari Which CI4 version are you using?

**Comment by arashsaffari** [comment]
@Martin-4Spaces  CodeIgniter 4.0.0-beta.3

**Comment by Martin-4Spaces** [comment]
Ok. I have to update OrmExtension to support beta.3 I'll get back to you.

**Comment by arashsaffari** [comment]
thanks

**Comment by Martin-4Spaces** [comment]
There you go. 1.0.0-beta.5.

**Comment by arashsaffari** [comment]
> There you go. 1.0.0-beta.5.

great job 👍

**Comment by BurkhalterY** [comment]
I am having the same error even though I am using CodeIgniter 4.0.3

**Comment by Martin-4Spaces** [comment]
@BurkhalterY Which version of CI4OrmExtension are you using?
The newest version is 1.0.0-beta.25.

**Comment by BurkhalterY** [comment]
I found. I did not install the beta but the 0.6
Thank you.
