### ISSUE TITLE
Get multiples Roles of a User

### ISSUE THREAD

**Issue by Gabriel-Arthur** [4spacesdk/CI4OrmExtension#10]
Following the documentation I have the database structure below

![bd](https://user-images.githubusercontent.com/57220261/106192550-196f3900-618b-11eb-8d13-9f80d60f3ec4.jpg)

how can i get all the roles of a user, because the code below

<pre><code>
$UserModel = new UserModel();
$user = $UserModel
    ->includeRelated(RoleModel::class)
    ->find(1);

var_dump($user->toArray());
</code></pre>

returns

<pre>
<code>
array (size=4)
  'id' => int 1
  'name' => string 'user 1' (length=6)
  'email' => string 'email user 1' (length=12)
  'roles' => 
    array (size=1)
      0 => 
        array (size=2)
          'id' => int 1
          'name' => string 'god' (length=3)
</code>
</pre>

I can even return correctly in an array like this

<pre>
<code>
array (size=4)
  'id' => int 1
  'name' => string 'user 1' (length=6)
  'email' => string 'email user 1' (length=12)
  'roles' => 
    array (size=2)
      0 => 
        array (size=2)
          'id' => int 1
          'name' => string 'god' (length=3)
      1 => 
        array (size=2)
          'id' => int 3
          'name' => string 'user' (length=4)
</code>
</pre>

doing something like that

<pre>
<code>
$UserModel = new UserModel();
$user = $UserModel->find(1);
$roles = $user->roles->find();

$user = $user->toArray();
$user['roles'] = $roles->allToArray();

var_dump($user);
</code>
</pre>

but, the instance of User don't have all the Roles and I can't set.

This is a problem?

Thanks a lot!

**Comment by Martin-4Spaces** [comment]
Hi Gabriel,
I think what is most important here, is to understant that `includeRelated` is the same as doing a join. So in your first example, you get 2 users returned. One for each related role.

This code should explain.
```
        // Joining user table with roles table. Resulting in one row for each role
        $userModel = new UserModel();
        $user = $userModel
            ->includeRelated(RoleModel::class)
            ->where('id', 1)
            ->find();
        Data::debug(get_class($this), "Joining user table with roles table. Resulting in one row for each role");
        Data::debug($user->allToArray());

        // Fetching roles user afterwards will put all roles on the user object
        $userModel = new UserModel();
        $user = $userModel->find(1);
        $user->roles->find();
        Data::debug(get_class($this), "Fetching roles user afterwards will put all roles on the user object");
        Data::debug($user->toArray());
```
Resulting in
![localhost_8580_Home_roles](https://user-images.githubusercontent.com/9819124/106229145-3b010c80-61ed-11eb-886d-571a00bf6c1d.png)

Here is the complete project I used to test this issue.
[CI4Playground.zip](https://github.com/4spacesdk/CI4OrmExtension/files/5891498/CI4Playground.zip)

**Comment by Gabriel-Arthur** [comment]
Omg, this is so simple!! 

Thank you !!
