### ISSUE TITLE
Find how to check if there is a result

### ISSUE THREAD

**Issue by happyadvertising** [4spacesdk/CI4OrmExtension#11]
Hello everyone, trying to figure out how to use this package and I was wondering how should I check there is a result from db.
Also is it possible to do like this because I didn't find a andWhere method.

```
      $row = $this->where('config_class', $class)
            ->where('config_property', $property)
        ->find();
```

Thank you for your time.

**Comment by Martin-4Spaces** [comment]
You can check this file for examples on where clauses https://github.com/4spacesdk/CI4OrmExtension/blob/master/Examples/Controllers/Where.php.

To check if there is a result, you can use `$row->exists()`.

**Comment by happyadvertising** [comment]
Thank you for the info
