### ISSUE TITLE
php >= 8.x compatibility

### ISSUE THREAD

**Issue by etcware** [4spacesdk/CI4OrmExtension#15]
We tried the library both with php 7 and php 8 and in this case we receive an error that seems this https://wiki.php.net/rfc/abstract_trait_method_validation that is implemented in php 8.
We don't go deeply because may there other problems, but to be inline with CI that is compatible with php 8 this library should be the same.

**Comment by Martin-4Spaces** [comment]
Thank you for raising this issue. I’ll take a look at php8.

**Comment by markkortleverwebavance** [comment]
Hi,

Any idea if and when there will be an update to make the package php8 compatible?

**Comment by Martin-4Spaces** [comment]
I hope to have time for this next week.

**Comment by Martin-4Spaces** [comment]
Here we go https://github.com/4spacesdk/CI4OrmExtension/releases/tag/1.0.3.
Let me know if you encounter any issues.
