### ISSUE TITLE
ErrorException #64

### ISSUE THREAD

**Issue by Schop** [4spacesdk/CI4OrmExtension#2]
Hi,

This looks primising, but when I install this, i get the following error when trying to use the model:

`ErrorException #64

Declaration of OrmExtension\Extensions\Model::save($entity) must be compatible with CodeIgniter\Model::save($data): bool`

**Comment by Martin-4Spaces** [comment]
Hi,

Make sure to use the latest version, currently it is 1.0.0-beta.22.
The error looks to be an old version.

**Comment by Schop** [comment]
When I install with comper, I get this: `"4spacesdk/ci4ormextension": "^0.6.0"`

I'm not very experienced with composer. Should I change the version number manually and update?

**Comment by Schop** [comment]
I found it, thank you!
