### ISSUE TITLE
Unwanted exception when putting casted data into array

### ISSUE THREAD

**Issue by Saddalim** [4spacesdk/CI4OrmExtension#25]
If you have a model with a field configured to be cast to an array-type (e.g. via 'json-array')
```
protected $casts = ['some_field' => 'json_array'];
```
Then when you call toArray() or jsonSerialize() on the resulting Entity, an exception is thrown at
```
Entity.php:174, OrmExtension\Extensions\Entity->__get()
EntityTrait.php:261, OrmExtension\Extensions\Entity->toArray()
Entity.php:402, CodeIgniter\Entity\Entity->jsonSerialize()
view.php:41, json_encode()
```
Because some_field is returned by the parent magic getter as an array and EntityTrait::toArray() forcibly tries to cast it into a string.

Suggested solution:
Check if the $field returned by the magic getter is of type string, only try to do the cast to the specific data type if it is, and leave other types as they are.

**Comment by Martin-4Spaces** [comment]
@Saddalim Good explanation and reasonable suggestion. 
I can see you already implemented the fix yourself. Would you like to create a PR?
