### ISSUE TITLE
Class "CodeIgniter\Entity" not found

### ISSUE THREAD

**Issue by pranaycb** [4spacesdk/CI4OrmExtension#30]
Codeigniter4 is no longer using that Entity namespace. Instead Codeigniter now use \CodeIgniter\Entity\Entity namespace. Could you please update the namespace in ci4ormextension\Extensions\Entity file?

**Comment by Martin-4Spaces** [comment]
@pranaycb I did that some time ago, https://github.com/4spacesdk/CI4OrmExtension/commit/be6c2c98be54ebc96b6046b4f89db66b584208c0
But missed the release part. I will create a new release now :) 
Thanks!

**Comment by pranaycb** [comment]
Appreciate your efforts. Great library for ORM for Codeigniter4 ❤
