### ISSUE TITLE
Not pre-fetching include

### ISSUE THREAD

**Issue by Schop** [4spacesdk/CI4OrmExtension#4]
Although the documentation says that relationship data is prefetched, I can't get it to work.

Working example from controller: 
```
$matchModel = new MatchModel();
$match = $matchModel->includeRelated(VenueModel::class)->find(1);
$match->venue->find();
echo $match->venue->name;
```
This actually does echo the Venue name, but this next example does not, although the documentation says it should:
```
$matchModel = new MatchModel();
$match = $matchModel->includeRelated(VenueModel::class)->find(1);
//$match->venue->find();
echo $match->venue->name;
```

**Comment by Martin-4Spaces** [comment]
Take a look at the `writeable/cache` folder. I think OrmExtension has cached som old field data :)
You can either delete the cache files manually, or create a spark command to do it.
Use this code to clear the cache:
`ModelDefinitionCache::getInstance()->clearCache();`

**Comment by Schop** [comment]
Thank you, that fixed that problem!
